mqtt:
  ip: localhost
  port: 1883
  qos: 1
  trigger_topic: churchill/camera/colour/trigger
  image_topic: churchill/camera/colour/image
camera:
  camera_type: dummy
  camera_id: colour
  dummy_location: ../data/dummy_camera/churchill/colour/4
  file_type: bmp
  capture_timeout: 10
trigger:
  trigger_type: software
lights: null
archiving:
  is_archived: 'true'
  archive_directory: ../data/images
  archive_parameters:
    archive_freq: daily
    archive_storage: 50
    archive_days: 30
