ip: localhost
port: 1883
trigger_topic: "test/camera/trigger"
image_topic: "test/camera/colour_image"
trigger_time_topic: "test/image/trigger_time"
message: null

camera:
  camera_type: dummy
  camera_id: "0001"
  pixel_format: BayerRG8
  trigger_type: software
  dummy_location: "C:/Users/AmyHarrison/camera_worker/camera-worker/test/"
  file_type: ".png"
  capture_timout: 10

archiving:
  is_archived: True
  archive_directory: "save_dir"
  archive_params:
    archive_freq: "daily"
    archive_storage: 50 # GB
    archive_days: 30 # days
